version: '3'
services:
  spiderman:
    image: tofu
    build: . 
    ports:
      - "80:3000"
    environment:
      REDIS: redis
    depends_on:
      - 'redis'
      - 'database'
    volumes:
      - ./:/code
  database:
    image: mongo:latest
  redis:
    image: redis:4.0.5-alpine
